# Generated by Django 3.0.5 on 2021-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('request_or_hidden', models.BooleanField(default=False)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('last_message', models.TextField(default='{\n        "is_read": "",\n        "creator": "",\n        "timestamp": "",\n        "content": ""\n    }')),
                ('group_img', models.ImageField(default='/defaults/no-img-group.jpeg', upload_to='group-pics/')),
                ('name', models.CharField(default='Chat', max_length=25)),
                ('id_chat', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('file_url', models.FileField(blank=True, default=None, null=True, upload_to='chat/')),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
