# Generated by Django 3.0.5 on 2021-06-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210621_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='last_message',
            field=models.TextField(default='{\n        "is_read": "",\n        "is_received": ""\n        "creator": "",\n        "timestamp": "",\n        "content": ""\n    }'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='', max_length=3300),
        ),
        migrations.AlterField(
            model_name='message',
            name='group_id',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='id_of_chat', to='myapp.Group'),
        ),
    ]
