# Generated by Django 3.0.5 on 2021-06-21 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
                ('profile_pic', models.ImageField(default='/defaults/no-img.jpeg', upload_to='pics/')),
                ('gender', models.BooleanField(default=True)),
                ('premium_days_left', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('subscription_id_stripe', models.TextField(default='')),
                ('customer_id_stripe', models.TextField(default='')),
                ('users_searched_day', models.IntegerField(default=0)),
                ('feeling', models.CharField(default='nothing', max_length=15)),
                ('about', models.CharField(default='A new user', max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('interests', models.CharField(default='[]', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('chat_list', models.ManyToManyField(default=None, related_name='users_chat_list', to='myapp.Group')),
                ('dating_with', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dating_with_user', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(default=None, related_name='_myuser_followers_+', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(default=None, related_name='_myuser_following_+', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(default=None, related_name='_myuser_friends_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifyLink',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('token',),
            },
        ),
    ]
