# Generated by Django 3.0.5 on 2021-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20210621_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='users_requested_date_day',
            field=models.IntegerField(default=0),
        ),
    ]
