# Generated by Django 3.0.5 on 2021-07-05 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_myuser_users_requested_date_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='block_list',
            field=models.ManyToManyField(default=None, related_name='_myuser_block_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
